language:  csharp
mono: none
dotnet: 5.0

env: 
    - PROJECT="Quiz"

script:
    - cd $PROJECT
    - cd $PROJECT
    - dotnet build
    - cd ..
    - | 
        if [[ -d "$PROJECT.Tests" ]]
        then 
          cd ${PROJECT}.Tests
          dotnet test
          cd ..
        fi
    - cd ..

